version: '3.7'

services:
  ncino-state-provision:
    image: state-provision
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: state-provision
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
